* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{aidan.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Caio Garcia
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Caio Garcia}
\photoR{2.8cm}{Perfil2023.jpeg}
\tagline{Cientista de Dados}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \homepage{caio-a-garcia.github.io}
  \email{caioag3@al.insper.edu.br}
  \phone{+55 34 99673 8500}
  \location{São Paulo, Brasil}
  \github{caio-a-garcia}
  \hspace{1.05cm}
  \linkedin{kaioviski/}
  \hspace{1.8cm}
  \dob{18 Dezembro 1996}
}
\makecvheader
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Personal Statement :ignore:
#+begin_export latex
 \begin{quote}
 ``Sou um Cientista de Dados com formação em Matemática e experiência profissional em desenvolvimento web.''
 \end{quote}
#+end_export
** Experiência
*** Sapiens :ignore:
{{{cvevent(Desenvolvedor No-Code, Sapiens Agro, Nov 2023 -- Mar 2024, Uberlândia\, MG\, Brasil)}}}

Utilizando a tecnologia no-code Bubble, desenvolvi uma plataforma ao redor de um serviço de previsão de custo de frete de commodities. Gerei visualizações interativas a partir das saídas do modelo de previsão (via API) assim como de dados de uso da plataforma.

{{{cvtag(Data Viz)}}}
{{{cvtag(Web Dev)}}}
{{{cvtag(No-Code)}}}
{{{cvtag(Bubble)}}}

*** Kyros - Clojure :ignore:
{{{par-div}}}
{{{cvevent(Desenvolvedor Fullstack, Kyros Tecnologia, Ago 2022 -- Abr 2023, Uberlândia\, MG\, Brasil)}}}

Trabalhei em uma aplicação Clojure full stack, tomando conta de tickets de suporte com meu time e pessoalmente puxando as principais demandas de novas features para o front.

{{{cvtag(GraphQL)}}}
{{{cvtag(Clojure)}}}

*** Kyros - Processos :ignore:
{{{par-div}}}
{{{cvevent(Analista de Processos, Kyros Tecnologia, Set 2021 -- Ago 2022, Uberlândia\, MG\, Brasil)}}}

Liderei um time multi-disciplinar na ideação e desenvolvimento de um projeto experimental em Realidade Virtual.

{{{cvtag(Unreal Engine)}}}
{{{cvtag(Processos)}}}
\break

** Projects
*** Active Learning Secondmind :ignore:noexport:

# {{{cvevent(Investigating Exploration-Exploitation in Multimodal Dynamical Systems (Academic), University of Bristol, May 2021 - Ongoing, Bristol\, UK)}}}
{{{cvevent(Exploration of Operatable Dynamics Modes in Multimodal Dynamical Systems, University of Bristol, May 2021 - Ongoing, Bristol\, UK)}}}

- Developing data-efficient techniques for exploration in multimodal dynamical systems.
- The goal of this project is to explore a single dynamics mode that is known to be operatable whilst avoiding other modes.
  # unoperatable capable of remaining in a single dynamics mode during exploration.

# {{{cvtag(JAX)}}}
{{{cvtag(Bayesian optimisation)}}}
{{{cvtag(Gaussian processes)}}}
{{{cvtag(Optimal control)}}}

*** Active Learning :ignore:

# {{{cvevent(Investigating Exploration-Exploitation in Multimodal Dynamical Systems (Academic), University of Bristol, May 2021 - Ongoing, Bristol\, UK)}}}
{{{cvevent(Optimal Control in Multimodal Dynamical Systems as Probabilistic Inference, University of Bristol, May 2021 - Ongoing, Bristol\, UK)}}}

- Developing data-efficient techniques for exploration in multimodal dynamical systems.
- The goal of this project is to explore a single dynamics mode that is known to be operatable whilst avoiding other modes.

{{{cvtag(Variational inference)}}}
{{{cvtag(Gaussian processes)}}}
{{{cvtag(Optimal control)}}}

** Newpage :ignore:
{{{new-page}}}

** Projects (Cont.)
*** Traj Opt :ignore:
# {{{divider}}}

{{{cvevent(Trajectory Optimisation in Learned Multimodal Dynamical Systems, University of Bristol, Sept 2019 - March 2021, Bristol\, UK)}}}

- Synergising Bayesian inference and Riemannian geometry to control multimodal dynamical systems.
   # Learning multimodal probabilistic transition dynamics.
- Finds trajectories that 1) remain in a desired dynamics mode, 2) avoid regions of the dynamics with high epistemic uncertainty.
- [[https://github.com/aidanscannell/trajectory-optimisation-in-learned-multimodal-dynamical-systems][\faGithub aidanscannell/trajectory-optimisation-in-learned-multimodal-dynamical-systems]]
# - [[https://www.aidanscannell.com/publication/trajectory-optimisation-in-learned-multimodal-dynamical-systems-via-latent-ode-collocation/paper.pdf][\faBook published @ ICRA 2021]]

{{{cvtag(JAX)}}}
{{{cvtag(Probabilistic geometries)}}}
{{{cvtag(Optimal control)}}}

*** SVGP :ignore:
{{{par-div}}}

{{{cvevent(Identifiable Mixtures of Sparse Variational Gaussian Process Experts, University of Bristol, Sept 2018 - Ongoing, Bristol\, UK)}}}

- Improving identifiability and scalability in the Mixtures of Gaussian Process Experts model with GP-based gating networks.
- Variational inference based on sparse GP approximations.
-  [[https://github.com/aidanscannell/mogpe][\faGithub aidanscannell/mogpe]]

{{{cvtag(GPflow)}}}
{{{cvtag(TensorFlow)}}}
{{{cvtag(Gaussian processes)}}}
{{{cvtag(Variational inference)}}}

*** GPJax :ignore:noexport:
{{{divider}}}

{{{cvevent(Gaussian Processes in JAX (Code), Emacs, March 2021 - Ongoing, Bristol\, UK)}}}

- Minimal Gaussian process library in JAX with a simple (custom) approach to state management.
- \faGithub [[https://github.com/aidanscannell/GPJax][aidanscannell/GPJax]]

{{{cvtag(Gaussian processes)}}}
{{{cvtag(Variational inference)}}}
{{{cvtag(JAX)}}}
{{{cvtag(SVGP)}}}

** A day of my life :noexport:
# #+begin_export latex
# % \medskip

# % \cvsection{A Day of My Life}

# % % Adapted from @Jake's answer from http://tex.stackexchange.com/a/82729/226
# % % \wheelchart{outer radius}{inner radius}{
# % % comma-separated list of value/text width/color/detail}
# % \wheelchart{1.5cm}{0.5cm}{%
# %   6/8em/accent!30/{Sleep,\\beautiful sleep},
# %   3/8em/accent!40/Hopeful novelist by night,
# %   8/8em/accent!60/Daytime job,
# %   2/10em/accent/Sports and relaxation,
# %   5/6em/accent!20/Spending time with family
# % }

# % % use ONLY \newpage if you want to force a page break for
# % % ONLY the current column
# % \newpage
# #+end_export

** Newpage :ignore:noexport:
{{{new-page}}}

** Volunteering
*** FARSCOPE Course Rep :ignore:
{{{cvevent(Cohort Representative, FARSCOPE CDT, Sept 2018 - Ongoing, Bristol\, UK)}}}
# - I represent myself and fellow CDT students in management meetings where I communicate ideas and information between students and management.
- Represent myself and my CDT peers in management meetings.
- Communicate information between students and management.

{{{cvtag(Communication)}}}
{{{cvtag(Interpersonal Skills)}}}

{{{par-div}}}

*** Code Club :ignore:
{{{cvevent(Club Leader, Code Club, Dec 2017 - April 2018, Junction 3 Library\, Bristol \, UK)}}}

# - I collaborated with [[https://codeclub.org/en/][Code Club]] and Bristol Libraries to set up and run a Code Club for young people aged 9-13.
# - Demonstrating my abi involved organising,  planning lessons and teaching
- Set up (and then ran) a [[https://codeclub.org/en/][Code Club]] for children aged 9-13.
- Led the organisation, planning and teaching of weekly lessons.
- Planned lessons to engage children by making coding fun.
- Extremely rewarding and reinforced my love for teaching.
# - @ Junction 3 Library in Easton, Bristol.

{{{cvtag(Leadership)}}}
{{{cvtag(Teaching)}}}
{{{cvtag(Communication)}}}
{{{cvtag(Active listening)}}}

*** Drivetrain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Technical Lead (Drivetrain), Formula Student, Jan 2015 - Jan 2016, Bristol\, UK)}}}

Each year, as part of Formula Student, students design, build and race a single seat race car.
- Finished 2nd in the National Class 2 competition in 2013/2014, I was then selected as the Drivetrain lead.
- This role improved my communication skills as I was leading weekly presentations.
- I developed my leadership skills through setting realistic objectives, effectively allocating work to the appropriate team members and monitoring outcomes.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

*** Snowboard Captain :ignore:noexport:
{{{par-div}}}

{{{cvevent(Snowboard Captain, University of Bristol Snowsports Club, Jan 2014 - Sept 2015, Bristol\, UK)}}}

- Organised multiple weekly training sessions, demonstrating my ability to plan and run events smoothly.
- Negotiated competitive prices for a growing member base within an inherently expensive sport.
- Responsible for aiding the smooth running of the club and helping to organise the annual university ski trip, with circa 1500 participants, working under pressure to manage people in high stress situations.
- Awarded the ‘Team of the Year’ award and full colours for my performances and contributions to the sport.

{{{cvtag(Teamwork)}}}
{{{cvtag(Leadership)}}}
{{{cvtag(Time Management)}}}

** Invited Talks
*** Geometry Talk :ignore:
{{{cvevent(Synergising Bayesian Inference and Probabilistic Geometries for Robotic Control, Cognitive Systems - Technical University of Denmark (DTU), 18 March 2021, Zoom)}}}
# - Presented a method for controlling multimodal dynamical systems synergising Bayesian inference and probabilistic geometries.
- Presented a method synergising Bayesian inference and probabilistic geometries to control multimodal dynamical systems.

{{{cvtag(Communication)}}}
{{{cvtag(Probabilistic geometries)}}}
{{{cvtag(Gaussian processes)}}}

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Skills
{{{cvtag(Python)}}}
{{{cvtag(NumPy)}}}
{{{cvtag(SciPy)}}}
{{{cvtag(Matplotlib)}}}

{{{divider}}}

{{{cvtag(Java)}}}
{{{cvtag(C++)}}}
{{{cvtag(MATLAB)}}}
{{{cvtag(ROS)}}}

{{{divider}}}


{{{cvtag(Git/GitHub)}}}
{{{cvtag(LaTeX)}}}
{{{cvtag(Org-mode)}}}
\break

** Educação
{{{cvevent(Programa Avançado em Data Science e Tomada de Decisão, Insper, Jul 2023 - Ongoing,)}}}
- \faBook Probabilistic Inference for Learning and Control in Multimodal Dynamical Systems

{{{divider}}}

{{{cvevent(Bacharelado em Matemática e Filosofia, Fordham University, Set 2015 - Mai 2019,)}}}

** Newpage :ignore:
#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT

** My Life Philosophy :noexport:
#+begin_export latex
% \begin{quote}
% ``Something smart or heartfelt, preferably in one sentence.''
% \end{quote}
#+end_export

** Achievements 
{{{cvachievement(\faTrophy, Full Sporting Colours, Awarded full colours for outstanding achievements in snowboarding. Multiple gold medals in British University Snowboard Championships.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Starting To Teach, Established myself as a confident\, enthusiastic and effective teacher who is able to engage\, encourage and develop students' learning.)}}}

{{{divider}}}

{{{cvachievement(\faTrophy,Bristol Plus Award, For undertaking a wide range of tasks to further enhance student skills - only 700 out of 23\,000 achieved this award per annum.)}}}

{{{divider}}}

{{{cvachievement(\faCertificate, Mary Jones Prize for Mathematics, For outstanding achievements in A Level mathematics @ Ripon Grammar School)}}}

{{{divider}}}

{{{cvachievement(\faTrophy, The Duke of Edinburgh's Award, Bronze/Silver/Gold)}}}

** Languages :noexport:
#+begin_export latex
% \cvsection{Languages}

% \cvskill{English}{5}
% \divider

% \cvskill{Spanish}{4}
% \divider

% \cvskill{German}{3}

% %% Yeah I didn't spend too much time making all the
% %% spacing consistent... sorry. Use \smallskip, \medskip,
% %% \bigskip, \vpsace etc to make ajustments.
% \medskip
#+end_export

# \newpage
** References
#+begin_export latex
% \cvref{name}{email}{mailing address}
\cvref{Prof.\ Arthur Richards}{University of Bristol}{arthur.richards@bristol.ac.uk}
% {Address Line 1\\Address line 2}
\divider
\cvref{Dr.\ Carl Henrik Ek}{University of Cambridge}{che29@cam.ac.uk}
% {Address Line 1\\Address line 2}
#+end_export

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export
