* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{aidan.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Caio Garcia
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Caio Garcia}
\photoR{2.8cm}{Perfil2023.jpeg}
\tagline{Cientista de Dados}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \homepage{caio-a-garcia.github.io}
  \email{caioag3@al.insper.edu.br}
  \phone{+55 34 99673 8500}
  \location{São Paulo, Brasil}
  \github{caio-a-garcia}
  \hspace{1.05cm}
  \linkedin{kaioviski/}
  \hspace{1.8cm}
  \dob{18 Dezembro 1996}
}
\makecvheader
#+end_export

** Personal Statement :ignore:
#+begin_export latex
 \begin{quote}
 ``Sou um Cientista de Dados com formação em Matemática e experiência em desenvolvimento web.''
 \end{quote}
#+end_export
* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Experiência
*** Sapiens :ignore:
{{{cvevent(Desenvolvedor No-Code, Sapiens Agro, Nov 2023 -- Mar 2024, Uberlândia\, MG\, Brasil)}}}

Utilizando a tecnologia no-code Bubble, desenvolvi uma plataforma ao redor de um serviço de previsão de custo de frete de commodities. Gerei visualizações interativas a partir das saídas do modelo de previsão (via API) assim como de dados de uso da plataforma.

{{{cvtag(Data Viz)}}}
{{{cvtag(Web Dev)}}}
{{{cvtag(No-Code)}}}
{{{cvtag(Bubble)}}}

*** Kyros - Clojure :ignore:
{{{par-div}}}
{{{cvevent(Desenvolvedor Fullstack, Kyros Tecnologia, Ago 2022 -- Abr 2023, Uberlândia\, MG\, Brasil)}}}

Trabalhei em uma aplicação Clojure full stack, tomando conta de tickets de suporte com meu time e pessoalmente puxando as principais demandas de novas features para o front.

{{{cvtag(GraphQL)}}}
{{{cvtag(Clojure)}}}

*** Kyros - Processos :ignore:
{{{par-div}}}
{{{cvevent(Analista de Processos, Kyros Tecnologia, Set 2021 -- Ago 2022, Uberlândia\, MG\, Brasil)}}}

Liderei um time multi-disciplinar na ideação e desenvolvimento de um projeto experimental em Realidade Virtual.

{{{cvtag(Unreal Engine)}}}
{{{cvtag(Processos)}}}
# \break

*** Huawei :ignore:
{{{par-div}}}
{{{cvevent(Estagiário Linguista, Huawei, Jul 2019 -- Set 2019,  Shanghai\, China)}}}

Conferi a qualidade de traduções do Inglês para o Português do SO mobile e serviços de nuvem da Huawei, tendo a oportunidade de me familiarizar com esses produtos.

# \break

*** LuizaLabs :ignore:
{{{par-div}}}
{{{cvevent(Estagiário Summer Camp, LuizaLabs, Jul 2019 -- Set 2019,  Shanghai\, China)}}}

Conferi a qualidade de traduções do Inglês para o Português do serviço operacional mobile e serviços de nuvem da Huawei, tendo a oportunidade de me familiarizar com esses produtos.

{{{cvtag(Agile)}}}
{{{cvtag(Scrum)}}}
\break

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Educação
{{{cvevent(Programa Avançado em Data Science e Tomada de Decisão, Insper, Jul 2023 - Ongoing,)}}}
- Modelos de aprendizado de máquina supervisionados e não supervisionados
  + \faBook An Introduction to Statistical Learning with Applications in R
- Big Data com PySpark em ambiente de nuvem
  + \faBook Data Analytics with Spark using Python

{{{divider}}}

{{{cvevent(Bacharelado em Matemática e Filosofia, Fordham University, Set 2015 - Mai 2019,)}}}
- Probabilidade e Estatística
- Cálculo e Equações Diferenciais
** Tecnologias
{{{cvtag(Python)}}}
{{{cvtag(Pandas)}}}
{{{cvtag(Spark)}}}
{{{cvtag(Matplotlib)}}}
{{{cvtag(Jupyter)}}}

{{{divider}}}

{{{cvtag(R)}}}
{{{cvtag(tidyverse)}}}
{{{cvtag(ggplot2)}}}
{{{cvtag(Rmd)}}}

{{{divider}}}


{{{cvtag(Git/GitHub)}}}
{{{cvtag(Docker)}}}
{{{cvtag(Guix)}}}
{{{cvtag(Quarto)}}}
\break

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export
