* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
*** Bibliography
# #+LATEX_HEADER: \DeclareNameAlias{sortname}{last-first}
#+LATEX_HEADER: \DeclareNameAlias{sortname}{given-family}
#+LATEX_HEADER: \addbibresource{aidan.bib}
# #+LATEX_HEADER: \usepackage[citestyle=numeric-comp, maxcitenames=1, maxbibnames=4, doi=false, isbn=false, eprint=true, backend=bibtex, hyperref=true, url=false, natbib=true]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber, sorting=nyvt, style=authoryear, firstinits]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=natbib, giveninits=true]{biblatex}
#+LATEX_HEADER: \usepackage[style=trad-abbrv,sorting=none,sortcites=true,doi=false,url=false,giveninits=true,hyperref]{biblatex}

** Exporter Settings
#+AUTHOR: Caio Garcia
#+EXPORT_FILE_NAME: ./cv-english.pdf
#+OPTIONS: toc:nil title:nil H:1
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header :ignore:
** Photo & Tagline :ignore:
#+begin_export latex
\name{Caio Garcia}
\photoR{2.8cm}{Perfil2023.jpeg}
\tagline{Data Scientist}
#+end_export

** Personal Info :ignore:
#+begin_export latex
\personalinfo{
  \homepage{caio-a-garcia.github.io}
  \email{caioag3@al.insper.edu.br}
  \phone{+55 34 99673 8500}
  \location{S찾o Paulo, Brasil}
  \github{caio-a-garcia}
  \hspace{1.05cm}
  \linkedin{kaioviski/}
  \hspace{1.8cm}
  \dob{December 18 1996}
}
\makecvheader
#+end_export

** Personal Statement :ignore:
#+begin_export latex
 \begin{quote}
 ``I am a Data Scientist with a Bachelor's in Mathematics and professional experience with web development.''
 \end{quote}
#+end_export
* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{2}
#+end_export
** Experience
*** Sapiens :ignore:
{{{cvevent(No-Code Developer, Sapiens Agro, Nov 2023 -- Mar 2024, Uberl창ndia\, MG\, Brasil)}}}

Using a no-code platform called Bubble, I developed a platform around a service for predicting the freight cost for agricultural commodities. I generated interactive visualizations from the API outputs generated from the data model, as well as from data generated by the platform itself.

{{{cvtag(Data Viz)}}}
{{{cvtag(Web Dev)}}}
{{{cvtag(No-Code)}}}
{{{cvtag(Bubble)}}}

*** Kyros - Clojure :ignore:
{{{par-div}}}
{{{cvevent(Fullstack Developer, Kyros Tecnologia, Aug 2022 -- Apr 2023, Uberl창ndia\, MG\, Brasil)}}}

I worked on a full stack Clojure application, sharing with my team the responsibility for support tickets and being personally responsible for the main new features for the front end.

{{{cvtag(GraphQL)}}}
{{{cvtag(Clojure)}}}
{{{cvtag(Full stack)}}}

*** Kyros - Processos :ignore:
{{{par-div}}}
{{{cvevent(Process Analyst, Kyros Tecnologia, Sep 2021 -- Aug 2022, Uberl창ndia\, MG\, Brasil)}}}

I led a cross-functional team through ideation and development of an experimental project with Virtual Reality.

{{{cvtag(Unreal Engine)}}}
{{{cvtag(Processes)}}}
# \break

*** LuizaLabs :ignore:
{{{par-div}}}
{{{cvevent(Summer Camp Intern, LuizaLabs, Jan 2020 -- Feb 2020,  Franca\, SP\, Brasil)}}}

I participated on two projects, helping with ideation and scope maintenance, at the innovation labs of big Brazilian retail company Magalu.

{{{cvtag(Agile)}}}
{{{cvtag(Scrum)}}}
\break

*** Huawei :ignore:
{{{par-div}}}
{{{cvevent(Linguist Intern, Huawei, Jul 2019 -- Sep 2019,  Shanghai\, China)}}}

I checked English to Portuguese translations for Huawei's mobile OS and cloud services, having an opportunity to familiarize myself with these services.

# \break

* CV Column 2 :ignore:
# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

** Education
{{{cvevent(Advanced Program in Data Science and Decision Making, Insper, Jul 2023 - Ongoing,)}}}
- Machine Learning: supervised and unsupervised models
  + \faBook An Introduction to Statistical Learning with Applications in R
- Big Data with PySpark on a cloud environment
  + \faBook Data Analytics with Spark using Python

{{{divider}}}

{{{cvevent(Bachelor's in Mathematics and Philosophy, Fordham University, Sep 2015 - May 2019,)}}}
- Probability and Statistics
- Calculus and Differential Equations
** Technologies
{{{cvtag(Python)}}}
{{{cvtag(Pandas)}}}
{{{cvtag(Spark)}}}
{{{cvtag(Matplotlib)}}}
{{{cvtag(Jupyter)}}}

{{{divider}}}

{{{cvtag(R)}}}
{{{cvtag(tidyverse)}}}
{{{cvtag(ggplot2)}}}
{{{cvtag(Rmd)}}}

{{{divider}}}


{{{cvtag(Git/GitHub)}}}
{{{cvtag(Docker)}}}
{{{cvtag(Guix)}}}
{{{cvtag(Quarto)}}}
\break

* Back Matter :ignore:
#+begin_export latex
\end{paracol}
\end{document}
#+end_export
